"""
EHR Dataset Exploratory Data Analysis (EDA) Reporter

This script reads the synthetic EHR dataset generated by generate_offline_ehr.py,
calculates data quality metrics, and generates two deliverables:
1. An interactive Plotly HTML report (eda_report.html)
2. A detailed Markdown report (eda_report.md)

Metrics Analyzed:
- Offline Skew Distribution (Ward and Event Type distributions)
- Distinct Cardinality of IDs (patients, visits, events, wards)
- Schema Evolution progression over time (null severity_level records)
- Offline Duplication rates (before vs after deduplication)
- Streaming Characteristics (events per minute/hour bursts, late arrival rates, and duplicate rates)
"""

import os
import argparse
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime
from loguru import logger

def format_percentage(val, total):
    return f"{val:,} ({val / total * 100:.2f}%)"

def analyze_offline_data(data_dir):
    logger.info("Loading offline datasets...")
    
    patients_path = os.path.join(data_dir, "patients.parquet")
    wards_path = os.path.join(data_dir, "wards.parquet")
    meta_path = os.path.join(data_dir, "event_metadata.parquet")
    visits_path = os.path.join(data_dir, "visits.parquet")
    events_path = os.path.join(data_dir, "events.parquet")
    
    # Read files
    df_patients = pd.read_parquet(patients_path)
    df_wards = pd.read_parquet(wards_path)
    df_meta = pd.read_parquet(meta_path)
    df_visits = pd.read_parquet(visits_path)
    df_events = pd.read_parquet(events_path)
    
    logger.info("Analyzing offline characteristics...")
    
    # 1. Cardinality
    cardinality = {
        "Patients": df_patients["patient_id"].nunique(),
        "Wards": df_wards["ward_id"].nunique(),
        "Event Metadata (Unique Definitions)": df_meta["event_type_id"].nunique(),
        "Visits (Total Record Count)": len(df_visits),
        "Visits (Unique IDs)": df_visits["visit_id"].nunique(),
        "Events (Total Record Count)": len(df_events),
        "Events (Unique IDs)": df_events["event_id"].nunique(),
    }
    
    # 2. Skew
    ward_counts = df_visits["ward_id"].value_counts()
    ward_pcts = df_visits["ward_id"].value_counts(normalize=True) * 100
    
    event_type_counts = df_events["event_type"].value_counts()
    event_type_pcts = df_events["event_type"].value_counts(normalize=True) * 100
    
    # 3. Schema Evolution: Nulls in older visits
    df_visits["admission_dt"] = pd.to_datetime(df_visits["admission_timestamp"])
    df_visits["admission_month"] = df_visits["admission_dt"].dt.to_period("M").astype(str)
    
    evolution_grouped = df_visits.groupby(["admission_month", df_visits["severity_level"].isna()]).size().unstack(fill_value=0)
    # Ensure columns are labeled cleanly
    evolution_grouped.columns = ["severity_present", "severity_missing"] # severity_level is Null is True or False
    # If standard groupby is True/False: True = IsNull (missing), False = NotNull (present)
    # Let's map it explicitly
    evol_null_map = df_visits.groupby(["admission_month", df_visits["severity_level"].isnull()]).size().unstack(fill_value=0)
    if True not in evol_null_map.columns:
        evol_null_map[True] = 0
    if False not in evol_null_map.columns:
        evol_null_map[False] = 0
    evol_null_map = evol_null_map.rename(columns={True: "severity_missing", False: "severity_present"})
    evol_null_map = evol_null_map.sort_index()
    
    # 4. Duplicate rate before/after dedup
    total_events = len(df_events)
    unique_events = df_events["event_id"].nunique()
    duplicate_count = total_events - unique_events
    duplicate_rate = (duplicate_count / total_events) * 100
    
    return {
        "df_patients": df_patients,
        "df_wards": df_wards,
        "df_meta": df_meta,
        "df_visits": df_visits,
        "df_events": df_events,
        "cardinality": cardinality,
        "ward_counts": ward_counts,
        "ward_pcts": ward_pcts,
        "event_type_counts": event_type_counts,
        "event_type_pcts": event_type_pcts,
        "evol_null_map": evol_null_map,
        "total_events": total_events,
        "unique_events": unique_events,
        "duplicate_count": duplicate_count,
        "duplicate_rate": duplicate_rate
    }



def generate_plotly_figures(offline_res):
    logger.info("Building Plotly visual elements...")
    figs = {}
    
    # 1. Ward Skew Chart
    df_visits = offline_res["df_visits"]
    fig_ward = px.pie(
        names=offline_res["ward_pcts"].index,
        values=offline_res["ward_counts"].values,
        title="Patient Visit Distribution Across Wards (Skewness)",
        color_discrete_sequence=px.colors.qualitative.Pastel
    )
    fig_ward.update_traces(textposition='inside', textinfo='percent+label')
    figs["ward_skew"] = fig_ward
    
    # 2. Event Type Distribution
    fig_event = px.bar(
        x=offline_res["event_type_pcts"].index,
        y=offline_res["event_type_counts"].values,
        labels={"x": "Clinical Event Type", "y": "Observation Count"},
        title="Distribution of Clinical Events",
        text=[f"{v/offline_res['total_events']*100:.1f}%" for v in offline_res["event_type_counts"].values],
        color=offline_res["event_type_pcts"].index,
        color_discrete_sequence=px.colors.qualitative.Safe
    )
    fig_event.update_traces(textposition='outside')
    figs["event_distribution"] = fig_event
    
    # 3. Schema Evolution Chart
    evol_df = offline_res["evol_null_map"].reset_index()
    fig_evol = go.Figure()
    fig_evol.add_trace(go.Bar(
        x=evol_df["admission_month"],
        y=evol_df["severity_missing"],
        name="Missing severity_level (v1.0 schema)",
        marker_color="indianred"
    ))
    fig_evol.add_trace(go.Bar(
        x=evol_df["admission_month"],
        y=evol_df["severity_present"],
        name="Populated severity_level (v2.0 schema)",
        marker_color="lightseagreen"
    ))
    fig_evol.update_layout(
        barmode='stack',
        title="Schema Evolution: Severity Level Presence Over Admission Months",
        xaxis_title="Admission Month",
        yaxis_title="Visits Volume",
        legend_title="Schema Attribute Status"
    )
    figs["schema_evolution"] = fig_evol
    
    return figs

def generate_markdown_report(offline_res, output_path):
    logger.info("Generating markdown text report...")
    
    patients = offline_res["df_patients"]
    df_visits = offline_res["df_visits"]
    null_deceased = patients["date_of_death"].isnull().sum()
    null_ethnic = patients["ethnic"].isnull().sum()
    
    md_content = f"""# Exploratory Data Analysis (EDA) Quality Report — EHR Dataset

This quality report summarizes the statistics, anomalies, and structural characteristics of the generated synthetic Electronic Health Record (EHR) dataset.

---

## 1. Cardinality and Entity Summary

This section details the distinct identifiers and physical record counts across all relational offline tables.

| Table Name | Total Record Count | Distinct Entity IDs | Description / Grain |
| :--- | :---: | :---: | :--- |
| **patients** | {len(patients):,} | {offline_res['cardinality']['Patients']:,} | One row per patient registry. |
| **wards** | {len(offline_res['df_wards']):,} | {offline_res['cardinality']['Wards']:,} | Hospital clinics/wards directory dimensions. |
| **event_metadata** | {len(offline_res['df_meta']):,} | {offline_res['cardinality']['Event Metadata (Unique Definitions)']:,} | Catalog lookup of clinical observations. |
| **visits** | {offline_res['cardinality']['Visits (Total Record Count)']:,} | {offline_res['cardinality']['Visits (Unique IDs)']:,} | Patient admission visits log (partitioned). |
| **events** | {offline_res['cardinality']['Events (Total Record Count)']:,} | {offline_res['cardinality']['Events (Unique IDs)']:,} | Granular clinical observations logs (partitioned). |

---

## 2. Offline Data Quality Issues & Distributions

### 2.1 Facility Skew (Wards)
To test downstream capacity constraints and partition skewness, a heavy bias was injected into `General_Ward`.

* **General_Ward**: {format_percentage(offline_res['ward_counts'].get('General_Ward', 0), offline_res['cardinality']['Visits (Unique IDs)'])} of total visits.
* **Pediatric_Ward**: {format_percentage(offline_res['ward_counts'].get('Pediatric_Ward', 0), offline_res['cardinality']['Visits (Unique IDs)'])} of total visits.
* **ICU_Ward**: {format_percentage(offline_res['ward_counts'].get('ICU_Ward', 0), offline_res['cardinality']['Visits (Unique IDs)'])} of total visits.
* **ER_Ward**: {format_percentage(offline_res['ward_counts'].get('ER_Ward', 0), offline_res['cardinality']['Visits (Unique IDs)'])} of total visits.

### 2.2 Patient Demographic Missing Values (Nulls)
Nullable fields in the patients table (expected sparsity):
* **date_of_death is NULL (alive patients)**: {format_percentage(null_deceased, len(patients))}
* **ethnic is NULL**: {format_percentage(null_ethnic, len(patients))}

### 2.3 Event Type Distributions
Clinical observations are partitioned across 4 distinct types:
* **vital**: {format_percentage(offline_res['event_type_counts'].get('vital', 0), offline_res['total_events'])}
* **lab**: {format_percentage(offline_res['event_type_counts'].get('lab', 0), offline_res['total_events'])}
* **medication**: {format_percentage(offline_res['event_type_counts'].get('medication', 0), offline_res['total_events'])}
* **diagnosis**: {format_percentage(offline_res['event_type_counts'].get('diagnosis', 0), offline_res['total_events'])}

### 2.4 Schema Evolution Verification
Visits prior to `2023-08-01` represent legacy systems where the `severity_level` column was missing.
* **v1.0 legacy visits (severity_level IS NULL)**: {format_percentage(val=(df_visits["admission_timestamp"] < datetime(2023, 8, 1)).sum(), total=len(df_visits))}
* **v2.0 modern visits (severity_level IS POPULATED)**: {format_percentage(val=(df_visits["admission_timestamp"] >= datetime(2023, 8, 1)).sum(), total=len(df_visits))}

### 2.5 Duplicate Record Rates (Events Table)
A 2.0% duplication rate was injected into the offline `events` fact logs to test deduplication processes.
* **Total Rows**: {offline_res['total_events']:,}
* **Unique Events**: {offline_res['unique_events']:,}
* **Duplicate Rows Injected**: {offline_res['duplicate_count']:,} ({offline_res['duplicate_rate']:.2f}% duplicate rate)

---

## 3. Visualizations

![EDA Report Charts](eda_report.png)
"""
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    logger.info(f"Saved markdown report to: {output_path}")
    print(md_content)


def generate_png_report(figs, png_path):
    logger.info("Composing combined PNG report...")

    from plotly.subplots import make_subplots
    import plotly.graph_objects as go

    # Build a 3-row combined figure
    combined = make_subplots(
        rows=3, cols=1,
        subplot_titles=[
            "Patient Visit Distribution Across Wards (Skewness)",
            "Distribution of Clinical Events",
            "Schema Evolution: Severity Level Presence Over Admission Months",
        ],
        vertical_spacing=0.10,
        specs=[[{"type": "domain"}], [{"type": "xy"}], [{"type": "xy"}]],
    )

    # Row 1 — Pie (ward skew): copy traces from the original figure
    for trace in figs["ward_skew"].data:
        combined.add_trace(trace, row=1, col=1)

    # Row 2 — Bar (event distribution)
    for trace in figs["event_distribution"].data:
        combined.add_trace(trace, row=2, col=1)

    # Row 3 — Stacked bar (schema evolution)
    for trace in figs["schema_evolution"].data:
        combined.add_trace(trace, row=3, col=1)

    combined.update_layout(
        height=1800,
        width=1400,
        title_text="EHR Synthetic Dataset — EDA Report",
        title_font_size=22,
        paper_bgcolor="white",
        plot_bgcolor="white",
        showlegend=True,
        barmode="stack",
        font=dict(family="Arial", size=13),
        margin=dict(t=100, b=60, l=80, r=80),
    )

    combined.write_image(png_path, scale=2)
    logger.info(f"PNG EDA report saved to: {png_path}")


def main():
    parser = argparse.ArgumentParser(description="EHR Dataset EDA Reporter")
    parser.add_argument("--data-dir", type=str, default=None,
                        help="Path to synthetic dataset directory (defaults to source/data/synthetic)")
    parser.add_argument("--output-dir", type=str, default=None,
                        help="Path to save report outputs (defaults to source/artifacts)")
                        
    args = parser.parse_args()
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    if args.data_dir:
        data_dir = args.data_dir
    else:
        data_dir = os.path.abspath(os.path.join(script_dir, "..", "..", "data", "synthetic"))
        
    if args.output_dir:
        output_dir = args.output_dir
    else:
        output_dir = os.path.abspath(os.path.join(script_dir, "..", "..", "artifacts"))
        
    os.makedirs(output_dir, exist_ok=True)
    
    # 1. Analyze offline data
    offline_res = analyze_offline_data(data_dir)

    # 2. Generate markdown text report
    md_path = os.path.join(output_dir, "eda_report.md")
    generate_markdown_report(offline_res, md_path)

    # 3. Generate Plotly figures
    figs = generate_plotly_figures(offline_res)

    # 4. Generate combined PNG report
    png_path = os.path.join(output_dir, "eda_report.png")
    generate_png_report(figs, png_path)

if __name__ == "__main__":
    main()
