# Trino catalog: PostgreSQL connector pointing to metastore-db

connector.name=postgresql
connection-url=jdbc:postgresql://127.0.0.1:5432/${ENV:METASTORE_DB_NAME}
connection-user=${ENV:METASTORE_DB_USER}
connection-password=${ENV:METASTORE_DB_PASSWORD}
