"""
EHR Dataset Exploratory Data Analysis (EDA) Reporter

This script reads the synthetic EHR dataset generated by generate_offline_ehr.py,
calculates data quality metrics, and generates two deliverables:
1. An interactive Plotly HTML report (eda_report.html)
2. A detailed Markdown report (eda_report.md)

Metrics Analyzed:
- Offline Skew Distribution (Ward and Event Type distributions)
- Distinct Cardinality of IDs (patients, visits, events, wards)
- Schema Evolution progression over time (null severity_level records)
- Offline Duplication rates (before vs after deduplication)
- Streaming Characteristics (events per minute/hour bursts, late arrival rates, and duplicate rates)
"""

import os
import argparse
import json
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime
from loguru import logger

def format_percentage(val, total):
    return f"{val:,} ({val / total * 100:.2f}%)"

def analyze_offline_data(data_dir):
    logger.info("Loading offline datasets...")
    
    patients_path = os.path.join(data_dir, "patients.parquet")
    wards_path = os.path.join(data_dir, "wards.parquet")
    meta_path = os.path.join(data_dir, "event_metadata.parquet")
    visits_path = os.path.join(data_dir, "visits")
    events_path = os.path.join(data_dir, "events")
    
    # Read files
    df_patients = pd.read_parquet(patients_path)
    df_wards = pd.read_parquet(wards_path)
    df_meta = pd.read_parquet(meta_path)
    df_visits = pd.read_parquet(visits_path)
    df_events = pd.read_parquet(events_path)
    
    logger.info("Analyzing offline characteristics...")
    
    # 1. Cardinality
    cardinality = {
        "Patients": df_patients["patient_id"].nunique(),
        "Wards": df_wards["ward_id"].nunique(),
        "Event Metadata (Unique Definitions)": df_meta["event_type_id"].nunique(),
        "Visits (Total Record Count)": len(df_visits),
        "Visits (Unique IDs)": df_visits["visit_id"].nunique(),
        "Events (Total Record Count)": len(df_events),
        "Events (Unique IDs)": df_events["event_id"].nunique(),
    }
    
    # 2. Skew
    ward_counts = df_visits["ward_id"].value_counts()
    ward_pcts = df_visits["ward_id"].value_counts(normalize=True) * 100
    
    event_type_counts = df_events["event_type"].value_counts()
    event_type_pcts = df_events["event_type"].value_counts(normalize=True) * 100
    
    # 3. Schema Evolution: Nulls in older visits
    df_visits["admission_dt"] = pd.to_datetime(df_visits["admission_timestamp"])
    df_visits["admission_month"] = df_visits["admission_dt"].dt.to_period("M").astype(str)
    
    evolution_grouped = df_visits.groupby(["admission_month", df_visits["severity_level"].isna()]).size().unstack(fill_value=0)
    # Ensure columns are labeled cleanly
    evolution_grouped.columns = ["severity_present", "severity_missing"] # severity_level is Null is True or False
    # If standard groupby is True/False: True = IsNull (missing), False = NotNull (present)
    # Let's map it explicitly
    evol_null_map = df_visits.groupby(["admission_month", df_visits["severity_level"].isnull()]).size().unstack(fill_value=0)
    if True not in evol_null_map.columns:
        evol_null_map[True] = 0
    if False not in evol_null_map.columns:
        evol_null_map[False] = 0
    evol_null_map = evol_null_map.rename(columns={True: "severity_missing", False: "severity_present"})
    evol_null_map = evol_null_map.sort_index()
    
    # 4. Duplicate rate before/after dedup
    total_events = len(df_events)
    unique_events = df_events["event_id"].nunique()
    duplicate_count = total_events - unique_events
    duplicate_rate = (duplicate_count / total_events) * 100
    
    return {
        "df_patients": df_patients,
        "df_wards": df_wards,
        "df_meta": df_meta,
        "df_visits": df_visits,
        "df_events": df_events,
        "cardinality": cardinality,
        "ward_counts": ward_counts,
        "ward_pcts": ward_pcts,
        "event_type_counts": event_type_counts,
        "event_type_pcts": event_type_pcts,
        "evol_null_map": evol_null_map,
        "total_events": total_events,
        "unique_events": unique_events,
        "duplicate_count": duplicate_count,
        "duplicate_rate": duplicate_rate
    }

def analyze_streaming_data(data_dir):
    logger.info("Loading streaming JSON logs...")
    stream_path = os.path.join(data_dir, "clinical_event_stream.json")
    
    with open(stream_path, "r", encoding="utf-8") as f:
        stream_records = json.load(f)
        
    df_stream = pd.DataFrame(stream_records)
    logger.info("Analyzing streaming characteristics...")
    
    # Parse timestamps
    df_stream["event_dt"] = pd.to_datetime(df_stream["event_timestamp"])
    df_stream["created_dt"] = pd.to_datetime(df_stream["created_ts"])
    
    # 1. Late Arrivals
    # Lag in minutes
    df_stream["lag_mins"] = (df_stream["created_dt"] - df_stream["event_dt"]).dt.total_seconds() / 60
    # True late arrivals are those delayed by more than 1 minute (excluding minor processing lag)
    late_arrivals = df_stream[df_stream["lag_mins"] > 1]
    late_arrival_rate = (len(late_arrivals) / len(df_stream)) * 100
    avg_lag = late_arrivals["lag_mins"].mean()
    
    # 2. Duplicates
    total_stream = len(df_stream)
    unique_stream = df_stream["event_id"].nunique()
    dupe_stream = total_stream - unique_stream
    dupe_stream_rate = (dupe_stream / total_stream) * 100
    
    # 3. Bursts analysis
    # Group by hour of the day (0 to 23)
    df_stream["event_hour"] = df_stream["event_dt"].dt.hour
    df_stream["event_minute"] = df_stream["event_dt"].dt.minute
    df_stream["time_of_day_str"] = df_stream["event_dt"].dt.strftime("%H:%M")
    
    # Let's count events per hour
    hourly_counts = df_stream["event_hour"].value_counts().sort_index()
    
    # Count events per minute of the day for finer granularity (to show 12:00-12:20 and 20:00-20:20 spikes)
    # Total minutes in day = 1440
    df_stream["minute_of_day"] = df_stream["event_hour"] * 60 + df_stream["event_minute"]
    minute_counts = df_stream.groupby("minute_of_day").size().reindex(range(1440), fill_value=0)
    
    return {
        "df_stream": df_stream,
        "total_stream": total_stream,
        "unique_stream": unique_stream,
        "dupe_stream": dupe_stream,
        "dupe_stream_rate": dupe_stream_rate,
        "late_arrival_rate": late_arrival_rate,
        "avg_lag": avg_lag,
        "hourly_counts": hourly_counts,
        "minute_counts": minute_counts
    }

def generate_plotly_figures(offline_res, stream_res):
    logger.info("Building Plotly visual elements...")
    figs = {}
    
    # 1. Ward Skew Chart
    df_visits = offline_res["df_visits"]
    fig_ward = px.pie(
        names=offline_res["ward_pcts"].index,
        values=offline_res["ward_counts"].values,
        title="Patient Visit Distribution Across Wards (Skewness)",
        color_discrete_sequence=px.colors.qualitative.Pastel
    )
    fig_ward.update_traces(textposition='inside', textinfo='percent+label')
    figs["ward_skew"] = fig_ward
    
    # 2. Event Type Distribution
    fig_event = px.bar(
        x=offline_res["event_type_pcts"].index,
        y=offline_res["event_type_counts"].values,
        labels={"x": "Clinical Event Type", "y": "Observation Count"},
        title="Distribution of Clinical Events",
        text=[f"{v/offline_res['total_events']*100:.1f}%" for v in offline_res["event_type_counts"].values],
        color=offline_res["event_type_pcts"].index,
        color_discrete_sequence=px.colors.qualitative.Safe
    )
    fig_event.update_traces(textposition='outside')
    figs["event_distribution"] = fig_event
    
    # 3. Schema Evolution Chart
    evol_df = offline_res["evol_null_map"].reset_index()
    fig_evol = go.Figure()
    fig_evol.add_trace(go.Bar(
        x=evol_df["admission_month"],
        y=evol_df["severity_missing"],
        name="Missing severity_level (v1.0 schema)",
        marker_color="indianred"
    ))
    fig_evol.add_trace(go.Bar(
        x=evol_df["admission_month"],
        y=evol_df["severity_present"],
        name="Populated severity_level (v2.0 schema)",
        marker_color="lightseagreen"
    ))
    fig_evol.update_layout(
        barmode='stack',
        title="Schema Evolution: Severity Level Presence Over Admission Months",
        xaxis_title="Admission Month",
        yaxis_title="Visits Volume",
        legend_title="Schema Attribute Status"
    )
    figs["schema_evolution"] = fig_evol
    
    # 4. Ingestion Late Arrival lag histogram
    df_stream = stream_res["df_stream"]
    late_df = df_stream[df_stream["lag_mins"] > 1]
    fig_lag = px.histogram(
        late_df,
        x="lag_mins",
        nbins=50,
        title="Distribution of Ingestion Lag for Late-Arriving Data",
        labels={"lag_mins": "Ingestion Delay (Minutes)", "count": "Event Count"},
        color_discrete_sequence=["orange"]
    )
    figs["ingestion_lag"] = fig_lag
    
    # 5. Stream Burst Traffic over Day
    min_counts = stream_res["minute_counts"]
    # Map minutes (0-1439) back to HH:MM format
    time_labels = [f"{m//60:02d}:{m%60:02d}" for m in range(1440)]
    fig_burst = go.Figure()
    fig_burst.add_trace(go.Scatter(
        x=time_labels,
        y=min_counts.values,
        mode='lines',
        name='Events / Min',
        line=dict(color='royalblue', width=2),
        fill='tozeroy',
        fillcolor='rgba(65, 105, 225, 0.2)'
    ))
    # Highlight burst windows
    fig_burst.add_vrect(x0="12:00", x1="12:20", fillcolor="red", opacity=0.15, layer="below", line_width=0, annotation_text="Shift Change Burst (12:00-12:20)")
    fig_burst.add_vrect(x0="20:00", x1="20:20", fillcolor="red", opacity=0.15, layer="below", line_width=0, annotation_text="Shift Change Burst (20:00-20:20)")
    fig_burst.update_layout(
        title="Real-Time Event Stream Volume Spikes (Traffic Bursts)",
        xaxis_title="Time of Day",
        yaxis_title="Observations per Minute",
        xaxis=dict(tickmode='array', tickvals=['00:00', '04:00', '08:00', '12:00', '16:00', '20:00', '23:59'])
    )
    figs["traffic_bursts"] = fig_burst
    
    return figs

def generate_markdown_report(offline_res, stream_res, output_path):
    logger.info("Generating markdown text report...")
    
    patients = offline_res["df_patients"]
    df_visits = offline_res["df_visits"]
    null_phones = patients["phone_number"].isnull().sum()
    null_addrs = patients["address"].isnull().sum()
    
    md_content = f"""# Exploratory Data Analysis (EDA) Quality Report — EHR Dataset

This quality report summarizes the statistics, anomalies, and structural characteristics of the generated synthetic Electronic Health Record (EHR) dataset.

---

## 1. Cardinality and Entity Summary

This section details the distinct identifiers and physical record counts across all relational offline tables.

| Table Name | Total Record Count | Distinct Entity IDs | Description / Grain |
| :--- | :---: | :---: | :--- |
| **patients** | {len(patients):,} | {offline_res['cardinality']['Patients']:,} | One row per patient registry. |
| **wards** | {len(offline_res['df_wards']):,} | {offline_res['cardinality']['Wards']:,} | Hospital clinics/wards directory dimensions. |
| **event_metadata** | {len(offline_res['df_meta']):,} | {offline_res['cardinality']['Event Metadata (Unique Definitions)']:,} | Catalog lookup of clinical observations. |
| **visits** | {offline_res['cardinality']['Visits (Total Record Count)']:,} | {offline_res['cardinality']['Visits (Unique IDs)']:,} | Patient admission visits log (partitioned). |
| **events** | {offline_res['cardinality']['Events (Total Record Count)']:,} | {offline_res['cardinality']['Events (Unique IDs)']:,} | Granular clinical observations logs (partitioned). |

---

## 2. Offline Data Quality Issues & Distributions

### 2.1 Facility Skew (Wards)
To test downstream capacity constraints and partition skewness, a heavy bias was injected into `General_Ward`.

* **General_Ward**: {format_percentage(offline_res['ward_counts'].get('General_Ward', 0), offline_res['cardinality']['Visits (Unique IDs)'])} of total visits.
* **Pediatric_Ward**: {format_percentage(offline_res['ward_counts'].get('Pediatric_Ward', 0), offline_res['cardinality']['Visits (Unique IDs)'])} of total visits.
* **ICU_Ward**: {format_percentage(offline_res['ward_counts'].get('ICU_Ward', 0), offline_res['cardinality']['Visits (Unique IDs)'])} of total visits.
* **ER_Ward**: {format_percentage(offline_res['ward_counts'].get('ER_Ward', 0), offline_res['cardinality']['Visits (Unique IDs)'])} of total visits.

### 2.2 Patient Demographic Missing Values (Nulls)
We allow up to a 5% missing rate on non-critical fields for demographic cleansing:
* **Missing Phone Numbers**: {format_percentage(null_phones, len(patients))}
* **Missing Addresses**: {format_percentage(null_addrs, len(patients))}

### 2.3 Event Type Distributions
Clinical observations are partitioned across 4 distinct types:
* **vital**: {format_percentage(offline_res['event_type_counts'].get('vital', 0), offline_res['total_events'])}
* **lab**: {format_percentage(offline_res['event_type_counts'].get('lab', 0), offline_res['total_events'])}
* **medication**: {format_percentage(offline_res['event_type_counts'].get('medication', 0), offline_res['total_events'])}
* **diagnosis**: {format_percentage(offline_res['event_type_counts'].get('diagnosis', 0), offline_res['total_events'])}

### 2.4 Schema Evolution Verification
Visits prior to `2023-08-01` represent legacy systems where the `severity_level` column was missing.
* **v1.0 legacy visits (severity_level IS NULL)**: {format_percentage(val=(df_visits["admission_timestamp"] < datetime(2023, 8, 1)).sum(), total=len(df_visits))}
* **v2.0 modern visits (severity_level IS POPULATED)**: {format_percentage(val=(df_visits["admission_timestamp"] >= datetime(2023, 8, 1)).sum(), total=len(df_visits))}

### 2.5 Duplicate Record Rates (Events Table)
A 2.0% duplication rate was injected into the offline `events` fact logs to test deduplication processes.
* **Total Rows**: {offline_res['total_events']:,}
* **Unique Events**: {offline_res['unique_events']:,}
* **Duplicate Rows Injected**: {offline_res['duplicate_count']:,} ({offline_res['duplicate_rate']:.2f}% duplicate rate)

---

## 3. Streaming Event Log Statistics

This section summarizes data quality metrics derived from the real-time event log `clinical_event_stream.json`.

### 3.1 Real-Time Ingestion Lag (Late Arrivals)
Labs and specific diagnostic reports arrive at the system significantly after the clinical event occurs.
* **Late Arrival Rate (Lag > 1 min)**: {stream_res['late_arrival_rate']:.2f}% of streaming events.
* **Average Ingestion Delay**: {stream_res['avg_lag']:.1f} minutes.

### 3.2 Streaming Duplication Rate
Kafka retries and monitor sensor failures are simulated with a 1.5% duplicate rate:
* **Total Stream Rows**: {stream_res['total_stream']:,}
* **Duplicate Events**: {stream_res['dupe_stream']:,} ({stream_res['dupe_stream_rate']:.2f}% duplication rate)

### 3.3 Traffic Bursts Analysis
Peak hour loads (representing nursing shift changes) occur daily at **12:00 - 12:20** and **20:00 - 20:20** where traffic multiplies by a factor of 30.
* **Baseline volume**: ~100 events / minute.
* **Peak burst volume**: ~3,000 events / minute.
"""
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    logger.info(f"Saved markdown report to: {output_path}")
    print(md_content)

def generate_html_report(figs, md_path, html_path):
    logger.info("Compiling interactive HTML report...")
    
    # Read markdown text to render it directly into HTML
    with open(md_path, "r", encoding="utf-8") as f:
        md_text = f.read()
        
    # Translate simple markdown tags to HTML structure
    html_desc = md_text.replace("\n", "<br>").replace("## ", "<h2>").replace("### ", "<h3>").replace("# ", "<h1>").replace("---", "<hr>")
    
    # Convert Plotly figures to HTML strings
    ward_div = figs["ward_skew"].to_html(full_html=False, include_plotlyjs='cdn')
    event_div = figs["event_distribution"].to_html(full_html=False, include_plotlyjs=False)
    evol_div = figs["schema_evolution"].to_html(full_html=False, include_plotlyjs=False)
    lag_div = figs["ingestion_lag"].to_html(full_html=False, include_plotlyjs=False)
    burst_div = figs["traffic_bursts"].to_html(full_html=False, include_plotlyjs=False)
    
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>EHR Synthetic Dataset Quality & EDA Report</title>
        <style>
            body {{
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                margin: 40px;
                background-color: #f7f9fc;
                color: #333;
            }}
            .container {{
                max-width: 1200px;
                margin: 0 auto;
                background-color: #fff;
                padding: 30px;
                border-radius: 12px;
                box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);
            }}
            h1, h2, h3 {{
                color: #2c3e50;
            }}
            h1 {{
                border-bottom: 2px solid #3498db;
                padding-bottom: 10px;
            }}
            h2 {{
                margin-top: 30px;
                border-bottom: 1px solid #ddd;
                padding-bottom: 5px;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
            }}
            table, th, td {{
                border: 1px solid #ddd;
            }}
            th, td {{
                padding: 12px;
                text-align: left;
            }}
            th {{
                background-color: #f2f2f2;
                color: #2c3e50;
            }}
            tr:nth-child(even) {{
                background-color: #f9f9f9;
            }}
            .chart-wrapper {{
                margin: 40px 0;
                background: #fdfdfd;
                border: 1px solid #eaeaea;
                padding: 15px;
                border-radius: 8px;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            {html_desc}
            
            <hr>
            <h1>Interactive Data Quality Visualizations</h1>
            
            <div class="chart-wrapper">
                {ward_div}
            </div>
            
            <div class="chart-wrapper">
                {event_div}
            </div>
            
            <div class="chart-wrapper">
                {evol_div}
            </div>
            
            <div class="chart-wrapper">
                {burst_div}
            </div>
            
            <div class="chart-wrapper">
                {lag_div}
            </div>
        </div>
    </body>
    </html>
    """
    
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    logger.info(f"Interactive HTML EDA report generated successfully at: {html_path}")

def main():
    parser = argparse.ArgumentParser(description="EHR Dataset EDA Reporter")
    parser.add_argument("--data-dir", type=str, default=None,
                        help="Path to synthetic dataset directory (defaults to source/data/synthetic)")
    parser.add_argument("--output-dir", type=str, default=None,
                        help="Path to save report outputs (defaults to data/synthetic)")
                        
    args = parser.parse_args()
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    if args.data_dir:
        data_dir = args.data_dir
    else:
        data_dir = os.path.abspath(os.path.join(script_dir, "..", "..", "data", "synthetic"))
        
    if args.output_dir:
        output_dir = args.output_dir
    else:
        output_dir = data_dir
        
    os.makedirs(output_dir, exist_ok=True)
    
    # 1. Analyze offline data
    offline_res = analyze_offline_data(data_dir)
    
    # 2. Analyze streaming data
    stream_res = analyze_streaming_data(data_dir)
    
    # 3. Generate markdown text report
    md_path = os.path.join(output_dir, "eda_report.md")
    generate_markdown_report(offline_res, stream_res, md_path)
    
    # 4. Generate Plotly figures
    figs = generate_plotly_figures(offline_res, stream_res)
    
    # 5. Generate interactive HTML report
    html_path = os.path.join(output_dir, "eda_report.html")
    generate_html_report(figs, md_path, html_path)

if __name__ == "__main__":
    main()
