#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${AIRFLOW_DB_USER:-airflow} WITH PASSWORD '${AIRFLOW_DB_PASSWORD:-airflow}';
    CREATE DATABASE ${AIRFLOW_DB_NAME:-airflow};
    GRANT ALL PRIVILEGES ON DATABASE ${AIRFLOW_DB_NAME:-airflow} TO ${AIRFLOW_DB_USER:-airflow};

    CREATE USER ${DATAHUB_DB_USER:-datahub} WITH PASSWORD '${DATAHUB_DB_PASSWORD:-datahub_password}';
    CREATE DATABASE ${DATAHUB_DB_NAME:-datahub};
    GRANT ALL PRIVILEGES ON DATABASE ${DATAHUB_DB_NAME:-datahub} TO ${DATAHUB_DB_USER:-datahub};

    CREATE USER ${METASTORE_DB_USER:-hive} WITH PASSWORD '${METASTORE_DB_PASSWORD:-hive}';
    CREATE DATABASE ${METASTORE_DB_NAME:-metastore};
    GRANT ALL PRIVILEGES ON DATABASE ${METASTORE_DB_NAME:-metastore} TO ${METASTORE_DB_USER:-hive};
EOSQL
