source:
  type: "kafka"
  config:
    connection:
      bootstrap: "127.0.0.1:${KAFKA_PORT}"
      schema_registry_url: "http://127.0.0.1:${SCHEMA_REGISTRY_PORT}"
      consumer_config:
          security.protocol: "PLAINTEXT"
    stateful_ingestion:
        enabled: false
    topic_patterns:
      deny:
        # DataHub internal topics — hide from catalog
        - "^_.*"                              # __consumer_offsets, _schemas
        - "^MetadataChangeLog.*"
        - "^MetadataChangeProposal.*"
        - "^MetadataAuditEvent.*"
        - "^DataHubUsageEvent.*"
        - "^PlatformEvent.*"
        - "^datahub.*"

sink:
  type: "datahub-rest"
  config:
    server: "${DATAHUB_GMS_URL}"
